services:
  live_chat:
    build: .
    image: live_chat:latest 
    container_name: live_chat_app
    restart: unless-stopped
    expose:
      - "3030" # Shared internally with Nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - live_chat
